INSERT INTO USERS(USER_ID, FULL_NAME, USERNAME, EMAIL, GENDER, USER_ROLE, PASSWORD_HASH) VALUES (1, 'Admin User', 'admin', 'admin@onlineappetite.com', 4, 1, '$2y$10$toIIxgiAiUgbL6qRp6zq9..ronjiS/C.bIxlocCsKa.LPHyVUaNCC');
INSERT INTO MANAGEMENTS(USER_ID, CONTACT_NO) VALUES (1, '+977 9843060387');
