CREATE TABLE users ( user_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, full_name VARCHAR(30) NOT NULL, username VARCHAR(30) NOT NULL UNIQUE, email VARCHAR(100) NOT NULL UNIQUE, street VARCHAR(100) NULL, city VARCHAR(100) NULL, state VARCHAR(100) NULL, postal VARCHAR(100) NULL, country VARCHAR(100) NULL, gender INTEGER NOT NULL, user_role INTEGER DEFAULT 3, password_hash VARCHAR(255) NOT NULL, image VARCHAR(100) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL );

CREATE TABLE managements ( management_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, contact_no VARCHAR(20) NOT NULL, FOREIGN KEY (user_id) REFERENCES user(user_id) );

CREATE TABLE customers ( customer_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, email_verified_at TIMESTAMP NULL, FOREIGN KEY (user_id) REFERENCES user(user_id) );

CREATE TABLE traders ( trader_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, verified_at TIMESTAMP NULL, contact_no VARCHAR(20) NOT NULL, trading_since DATETIME NOT NULL, business_type INT(1) NOT NULL, preferred_payments VARCHAR(30) NOT NULL, message VARCHAR(200) NOT NULL, status INTEGER DEFAULT 1, FOREIGN KEY (user_id) REFERENCES user(user_id) );

CREATE TABLE slot( slot_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30) NOT NULL created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL );

CREATE TABLE order( order_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, slot_id INT FOREIGN KEY REFERENCES slot(slot_id), cart_id INT FOREIGN KEY REFERENCES cart(cart_id), order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE category( category_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL );

CREATE TABLE shop( shop_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, address VARCHAR(50) NOT NULL, trader_id INT FOREIGN KEY REFERENCES trader(trader_id), name VARCHAR(30) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL );

CREATE TABLE product( product_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30) NOT NULL, category_id INT FOREIGN KEY REFERENCES category(category_id), price FLOAT NOT NULL, quantity INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL );

CREATE TABLE disCOUNT( discount_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, rate FLOAT NOT NULL, product_id INT FOREIGN KEY REFERENCES product(product_id), category_id INT FOREIGN KEY REFERENCES category(category_id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL );

CREATE TABLE cart( cart_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, product_id INT FOREIGN KEY REFERENCES product(product_id), customer_id INT FOREIGN KEY REFERENCES customer(customer_id), quantity INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL );

CREATE TABLE payment( payment_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, order_id INT FOREIGN KEY REFERENCES order(order_id), amount FLOAT NOT NULL, ); 