CREATE TABLE users ( user_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, full_name VARCHAR(30) NOT NULL, username VARCHAR(30) NOT NULL UNIQUE, email VARCHAR(100) NOT NULL UNIQUE, street VARCHAR(100) NULL, city VARCHAR(100) NULL, state VARCHAR(100) NULL, postal VARCHAR(100) NULL, country VARCHAR(100) NULL, gender INTEGER NOT NULL, user_role INTEGER DEFAULT 3, password_hash VARCHAR(255) NOT NULL, image VARCHAR(100) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL );

CREATE TABLE managements ( management_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, contact_no VARCHAR(20) NOT NULL, FOREIGN KEY (user_id) REFERENCES user(user_id) );

CREATE TABLE customers ( customer_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, email_verified_at TIMESTAMP NULL, FOREIGN KEY (user_id) REFERENCES user(user_id) );

CREATE TABLE traders ( trader_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, verified_at TIMESTAMP NULL, contact_no VARCHAR(20) NOT NULL, trading_since DATETIME NOT NULL, business_type INT(1) NOT NULL, preferred_payments VARCHAR(30) NOT NULL, message VARCHAR(200) NOT NULL, status INTEGER DEFAULT 1, FOREIGN KEY (user_id) REFERENCES user(user_id) );

CREATE TABLE shops ( shop_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, trader_id INTEGER NOT NULL, shop_name VARCHAR(30) NOT NULL, verified_on DATE NULL, gov_no VARCHAR(30) NOT NULL, address VARCHAR(50) NOT NULL, contact_no VARCHAR(20) NOT NULL, shop_type VARCHAR(20) NOT NULL, description VARCHAR(200) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL, FOREIGN KEY (trader_id) REFERENCES trader (trader_id) );

CREATE TABLE categories ( category_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, category_name VARCHAR(30) NOT NULL, description VARCHAR(200) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL );

CREATE TABLE products ( product_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, product_name VARCHAR(30) NOT NULL, category_id INTEGER NOT NULL, confirmed_on DATE NULL, price INTEGER NOT NULL, stock INTEGER NOT NULL, shop_id INTEGER NOT NULL, description VARCHAR(200) NOT NULL, image1 VARCHAR(50) NOT NULL, image2 VARCHAR(50) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL, FOREIGN KEY (category_id) REFERENCES category (category_id), FOREIGN KEY (shop_id) REFERENCES shop (shop_id) );CREATE TABLE cart( cart_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, product_id INT FOREIGN KEY REFERENCES product(product_id), customer_id INT FOREIGN KEY REFERENCES customer(customer_id), quantity INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL );

CREATE TABLE order( order_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, slot_id INT FOREIGN KEY REFERENCES slot(slot_id), cart_id INT FOREIGN KEY REFERENCES cart(cart_id), order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE discount( discount_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, rate FLOAT NOT NULL, product_id INT FOREIGN KEY REFERENCES product(product_id), category_id INT FOREIGN KEY REFERENCES category(category_id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL );

CREATE TABLE payment( payment_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, order_id INT FOREIGN KEY REFERENCES order(order_id), amount FLOAT NOT NULL, ); 